### ISSUE TITLE
handmade.cpp and handmade.h are still present in the repository

### ISSUE THREAD

**Issue by tclamb** [itfrombit/osx_handmade#3]
Whenever you accidentally add handmade.{cpp,h} back into the tree, it's available by navigating to the mistaken commit (for example, here's the source files from day 27: [h](https://github.com/itfrombit/osx_handmade/blob/ad00dea784d2784b87cd0a4d7c7e408aae108c79/handmade/handmade.h), [cpp](https://github.com/itfrombit/osx_handmade/blob/ad00dea784d2784b87cd0a4d7c7e408aae108c79/handmade/handmade.cpp)).

To remove them from the tree, follow the instructions [here](https://help.github.com/articles/remove-sensitive-data/).

**Comment by itfrombit** [comment]
Removed old references to handmade.{cpp,h}.
