### ISSUE TITLE
./osx_asset_builder.h:35:10: fatal error: 'stb_truetype.h' file not found

### ISSUE THREAD

**Issue by SethArchambault** [itfrombit/osx_handmade#7]
Just a note, the current build is missing https://raw.githubusercontent.com/nothings/stb/master/stb_truetype.h

so it generates this error:

```
./osx_asset_builder.h:35:10: fatal error: 'stb_truetype.h' file not found
```
Quick fix, just thought you'd like to know!

**Comment by itfrombit** [comment]
osx_asset_builder has been deprecated in favor of osx_hhfont and in-game asset processing. I wrote a macOS version of hhfont using the native CoreText framework instead of stb_truetype so this include file is no longer needed.
